name: Compilar APK (Android)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v4

      - name: Compilar o APK com Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Publicar o APK
        uses: actions/upload-artifact@v4
        with:
          name: rastreadorcla-apk
          path: ${{ steps.buildozer.outputs.filename }}
          if-no-files-found: error